package com.danielsan.natapi.services

import com.danielsan.natapi.models.User
import com.danielsan.natapi.resources.AuthResource.Credential

import scala.concurrent.Await
import scala.concurrent.duration._

class AuthServiceImplSpec extends BaseSpec {

  before {
    server.prepare()

    server.addUser(User(-1, "daniel", "daniel@mail.com", "1234"))
    server.addUser(User(-1, "jujuba", "jujuba@mail.com", "senha"))
  }

  describe("Testing login service") {
    it("Should return a token if user login with correct credentials") {
      val result = Await.result(server.impl.authService.login(Credential("daniel@mail.com", "1234")), 3.seconds)
      assert(result.isLeft)
    }

    it("Should return a NotFoundException if trying to login with non existing email") {
      val result = Await.result(server.impl.authService.login(Credential("random@mail.com", "1234")), 3.seconds)
      assert(result.isRight)
      assert(result.getOrElse(null).isInstanceOf[Service.NotFoundException])
    }

    it("Should return a PermissionDeniedException if trying to login with a wrong password") {
      val result = Await.result(server.impl.authService.login(Credential("daniel@mail.com", "4432")), 3.seconds)
      assert(result.isRight)
      assert(result.getOrElse(null).isInstanceOf[Service.PermissionDeniedException])
    }
  }

  describe("Testing payload validation service (auth method)") {
    it("Should correctly decode a valid payload generated by the login service") {
      val Left(token) = Await.result(server.impl.authService.login(Credential("daniel@mail.com", "1234")), 3.seconds)

      val result = server.impl.authService.auth(token.token)

      assert(result.isLeft)
      assert(result.left.getOrElse(null).email == "daniel@mail.com")
    }

    it("Should return a PermissionDeniedException trying to decode a invalid token") {
      val result = server.impl.authService.auth("jujuba")

      assert(result.isRight)
      assert(result.getOrElse(null).isInstanceOf[Service.PermissionDeniedException])
    }

    it("Should return a MissingParameterException trying to decode a null token") {
      val result = server.impl.authService.auth(null)

      assert(result.isRight)
      assert(result.getOrElse(null).isInstanceOf[Service.MissingParameterException])
    }
  }
}
